# YAML configuration of Terreslam

# General
/terreslam/logsdir: "~/outputs/unorganized/terreslam"
/terreslam/max_depth: 120.0  #for Kinect 6.0

# Comms
/terreslam/frame_id: "base_link"
/terreslam/frame_id/odom: "/terreslam/odom"
/terreslam/frame_id/cloud: "/terreslam/cloud"
/terreslam/frame_id/plane: "/terreslam/cloud/plane"
/terreslam/frame_id/sub_lidar: "/adapt/lidar"
/terreslam/frame_id/sub_cam: "/adapt/cam"
/terreslam/frame_id/sub_cam_depth: "/adapt/cam_depth"
/terreslam/frame_id/sub_cam_info: "/adapt/camera_info"

# Plane Detector
/terreslam/PD/debug: true
/terreslam/PD/theta: 9
/terreslam/PD/phi: 18
/terreslam/PD/d: 1
/terreslam/PD/max_plane: 99
/terreslam/PD/min_plane_size: 800
/terreslam/PD/thres_angle: 15.0
/terreslam/PD/thres_dist: 0.5
# /terreslam/PD/thres_color: 

# Plane Processor
/terreslam/PP/debug: true
