# YAML configuration of Terreslam
#IMPORTANT: do not let an unfinished depth leaf of the yaml tree entrees (unexpected behabiour)

# General
/terreslam/logsdir: '/home/ivan/outputs/terreslam/unorganized'
/terreslam/max_depth: 120.0  #for Kinect 6.0

# Comms
/terreslam/frame_id/base: 'base_link'
/terreslam/frame_id/odom: '/terreslam/odom'
/terreslam/frame_id/cloud: '/terreslam/cloud'
/terreslam/frame_id/cloud_xy: '/terreslam/cloud_xy'
/terreslam/frame_id/cloud_filtered: '/terreslam/cloud_filtered'
/terreslam/frame_id/cloud_filtered_blobs: '/terreslam/cloud_filtered_blobs'
/terreslam/frame_id/cloud_plane: '/terreslam/cloud_plane'
/terreslam/frame_id/sub_lidar: '/adapt/lidar'
/terreslam/frame_id/sub_cam: '/adapt/cam'
/terreslam/frame_id/sub_cam_depth: '/adapt/cam_depth'
/terreslam/frame_id/sub_cam_info: '/adapt/camera_info'

# Plane Filter
/terreslam/PF/threshold: 0.05
/terreslam/PF/highpass: true

# Plane Detector
/terreslam/PD/debug: true
/terreslam/PD/theta: 9
/terreslam/PD/phi: 18
/terreslam/PD/d: 1
/terreslam/PD/max_plane: 99
/terreslam/PD/min_plane_size: 800
/terreslam/PD/thres_angle: 15.0
/terreslam/PD/thres_dist: 0.5
# /terreslam/PD/thres_color: 

# Blob Detector
/terreslam/BD/tolerance: 0.28
/terreslam/BD/min_size: 20
/terreslam/BD/max_size: 3000
/terreslam/BD/alpha: 0.7
/terreslam/BD/thres_xz: 0.025
/terreslam/BD/thres_radius: 0.5

# Plane Processor
/terreslam/PP/debug: true
