# YAML configuration of Terreslam

# General
/terreslam/logsdir: "/home/icaminal/outputs/unorganized/terreslam"
/terreslam/max_depth: 120.0  #for Kinect 6.0

# Comms
/terreslam/frame_id: "base_link"
/terreslam/odom_frame_id: "/terreslam/odom"
/terreslam/cloud_frame_id: "/terreslam/cloud"
/terreslam/plane_frame_id: "/terreslam/cloud/plane"
/terreslam/sub_lidar_frame_id: "/adapt/lidar"
/terreslam/sub_cam_frame_id: "/adapt/cam"
/terreslam/sub_cam_depth_frame_id: "/adapt/cam_depth"
/terreslam/sub_cam_info_frame_id: "/adapt/camera_info"

# Plane Detector
/terreslam/PD/debug: true
/terreslam/PD/theta: 9
/terreslam/PD/phi: 18
/terreslam/PD/d: 1
/terreslam/PD/max_plane: 99
/terreslam/PD/min_plane_size: 800
/terreslam/PD/thres_angle: 15.0
/terreslam/PD/thres_dist: 0.5
# /terreslam/PD/thres_color: 

# Plane Processor
/terreslam/PP/debug: true
