# YAML configuration of Terreslam General
#IMPORTANT: do not let an unfinished depth leaf of the yaml tree entrees (unexpected behabiour)

# General
logsdir: '/home/ivan/outputs/terreslam/unorganized'
max_depth: 120.0  #for Kinect 6.0

# Comms
base_topic/odom: 'odom'
base_topic/cloud: 'cloud'
base_topic/cloud_xy: 'cloud_xy'
base_topic/cloud_filtered: 'cloud_filtered'
base_topic/cloud_filtered_blobs: 'cloud_filtered_blobs'
base_topic/cloud_keypoints: 'cloud_keypoints'
base_topic/cloud_plane: 'cloud_plane'
base_topic/normal_filtered: 'normal_filtered'
base_topic/blob_matches: 'blob_matches'
base_topic/dd_keypoint_matches: 'dd_keypoint_matches'
base_topic/ddd_keypoint_matches: 'ddd_keypoint_matches'
base_topic/sub_lidar: '/adapt/lidar'
base_topic/sub_cam: '/adapt/cam'
base_topic/sub_cam_depth: '/adapt/cam_depth'
base_topic/sub_cam_info: '/adapt/camera_info'